### ISSUE TITLE
Could I please have some guidance?

### ISSUE THREAD

**Issue by pranavathreya** [chalet-org/chalet-example-sfml#1]
Sorry, I have successfully installed Chalet and initialized a Chalet project. What is the next step to accessing the SFML libraries? Please bear with me as I am completely new to C++ and SFML.

**Comment by rewrking** [comment]
In theory you should be able to clone this repo, cd into the directory and run `chalet build` and it will pull down SFML for you. Everything that describes how it does this is the `chalet.json` There's a VS Code extension you can use to try it inside of VS code, and of course there is documentation available on the website.

**Comment by pranavathreya** [comment]
Thank you so much for the direction, I will try this and get back to you! Is it possible you could add these instructions to the README? It was hard to infer all this from the current doc.
